### PR TITLE
Correct capitalization of 'atbash' to 'Atbash'

### PR DESCRIPTION
**Pull request by tasxatzial**

### CODE REVIEW

**Review by BethanyG — APPROVED** [review]

**Review by Cool-Katt — APPROVED** [review]

**Comment by BNAndras** [comment]
https://github.com/exercism/problem-specifications/blob/a0679b3c55aa0a3801bb05b2e2b2e6235f71762d/exercises/affine-cipher/description.md?plain=1#L7 includes another lowercased Atbash reference.

**Comment by BNAndras** [comment]
Also, if it doesn't cause additional churn for tracks with test generators, the comments in `atbash-cipher` tests.toml also use the lowercased Atbash.

**Comment by tasxatzial** [comment]
So far 'Atbash' is incorrectly capitalized in:

https://github.com/exercism/problem-specifications/blob/a0679b3c55aa0a3801bb05b2e2b2e6235f71762d/exercises/affine-cipher/description.md?plain=1#L7

https://github.com/exercism/problem-specifications/blob/a0679b3c55aa0a3801bb05b2e2b2e6235f71762d/exercises/atbash-cipher/metadata.toml?plain=1#L2

https://github.com/exercism/problem-specifications/blob/a0679b3c55aa0a3801bb05b2e2b2e6235f71762d/exercises/atbash-cipher/canonical-data.json?plain=1#L5

https://github.com/exercism/problem-specifications/blob/a0679b3c55aa0a3801bb05b2e2b2e6235f71762d/exercises/atbash-cipher/canonical-data.json?plain=1#L6

I'll update those too, if needed. I just need to know which ones.

**Comment by IsaacG** [comment]
I think it would be good to update them all to be consistent.

**Review by IsaacG — APPROVED** [review]

**Review by BNAndras — APPROVED** [review]

**Review by iHiD — APPROVED** [review]

**Comment by kotp** [comment]
* [403] [https://www.4clojure.com/](https://www.4clojure.com/) | Failed: Network error: Forbidden
This is returning the 403 from the website itself, and so this fails correctly.

This test is correctly failing, but not for reasons of this PR.

**Comment by BNAndras** [comment]
That was fixed in #2487 so we just need a rebase.

**Comment by tasxatzial** [comment]
@BNAndras You are referring to this PR? It doesn't seem to be conflicting with the main branch. Only the link check fails, which doesn't affect anything.

**Comment by kotp** [comment]
> @BNAndras You are referring to this PR? It doesn't seem to be conflicting with the main branch. Only the link check fails, which doesn't affect anything.

It is not that it is conflicting, it is that it out of date to what it is based on, not allowing the CI tests to pass.  If you check out main, get that branch up to date locally, and then rebase this branch to that, and push it up, you will find that the updated changes are in place allowing the CI test to pass.

The commands that I would do would be something like this:

```sh
git checkout main
git pull upstream main
git checkout atbash-cipher
git rebase upstream//main
git push origin atbash-cipher
```

Provided, of course, that the remote for the exercism repository is `upstream`.

You may need to force push, which is fine, as this is your own branch, not the history on main on the "canonical repository".

**Comment by iHiD** [comment]
>```
> git checkout main
> git pull upstream main
> git checkout atbash-cipher
> git rebase upstream//main
> git push origin atbash-cipher
> ```

If you want a few less keystrokes, you can also do merge some of those lines.
```
git checkout atbash-cipher
git pull --rebase upstream main
git push origin atbash-cipher
```

**Comment by IsaacG** [comment]
> I understand that the CI check links does not pass, what I don't understand why they need to pass?
> 
> For example, commits on 9 Oct, 22 Oct, 24 Oct, were all having the same issue with the failing links.

There was a known issue with the check.  People were discussing it and trying to figure out how to beat deal with it. While there was a known issue with the check, it was reasonable to ignore the failures. 

The issue has since been fixed and the check should now be working. There is no longer any reason for the tests to be failing.

**Comment by Cool-Katt** [comment]
@tasxatzial looks like your fork of the repo is a few commits behind so it didn't get the fux that Isaac was talking about. (It's relatively recent, at least the specific case that's making the CI fail here)

**Comment by tasxatzial** [comment]
Ok, so no particular reason other than making the checks pass. When BNAndras said it was needed, I thought there was a more serious issue, like deployment failing or something similar, hence the question.

Rebased.

**Comment by BNAndras** [comment]
Thanks. I was just clarifying what needed to be after KOTP highlighted the failing test. The PR itself can’t be merged without approval from the code owner.

**Comment by kotp** [comment]
> git checkout atbash-cipher
> git pull --rebase upstream main
> git push origin atbash-cipher

Know that the shorter way will not update your main, though, but will only rebase the branch to upstream/main.

Probably not a problem if you are aware, but may cause confusion if you are not.

**Comment by kotp** [comment]
Also, thanks @tasxatzial for the rebase, and @BNAndras for the clarification, @iHiD for the lesson in git efficiency, and @Cool-Katt for reiteratig and @IsaacG for the time travel exploration!

**Comment by BNAndras** [comment]
@exercism/maintainers-admin, can we get an approval? Please and thank you.

**Review by keiravillekode — APPROVED** [review]

**Comment by IsaacG** [comment]
+cc @ErikSchierboom

**Comment by iHiD** [comment]
> @exercism/maintainers-admin, can we get an approval? Please and thank you.

Currently - this is only @ErikSchierboom.

@ErikSchierboom Could you remove `maintainers-admin` from all the tooling repos please (now we have guardians). Then I can join the team and do this stuff alongside you? If I join the team now, I'll get subscribed to hundreds of repos which I don't want :)

---

In the meantime, I'll just merge this using admin priviledges.

**Pull request merged**
