### PR TITLE
two-bucket: fix incorrect test case

### LINKED ISSUE #911: two-bucket: incorrect test case in canonical data?
According to the [README] for the exercise, valid moves include:
>pouring from one bucket to another
>emptying one bucket and doing nothing to the other
>filling one bucket and doing nothing to the other

The only other restriction stated is
>That means, when starting with the larger bucket full, you are NOT allowed at any point to have the smaller bucket full and the larger bucket empty (aka, the opposite starting point)

In other words, if one bucket is full, and the other empty, the full bucket must be the starting bucket.

The last test case description says ["Measure using bucket one of size 2 and bucket two of size 3 - start with bucket one and end with bucket two"](https://github.com/exercism/problem-specifications/blob/df076b2bd75e06e42a2ad0cb7eb0d5a8bdccd9f6/exercises/two-bucket/canonical-data.json#L70-L84) 

With the above rules, what disqualifies the following from being a valid solution for the above test case?
(2 moves): `(fill first bucket, as directed) [2, 0] -> (fill second bucket) [2, 3]`

### PR DESCRIPTION
**Pull request by cmccandless**
Resolves #911

### CODE REVIEW

**Comment by Insti** [comment]
1.2.0 ?

The result of a test has changed, this may mean solutions that once passed now fail.
1.1.1 would be fixing a typo in the test name or similar.

(plus or minus whatever #938 decides.)

**Comment by rpottsoh** [comment]
>1.2.0 ?

Works for me.  @cmccandless please change `"version":` to equal 1.2.0.

**Comment by cmccandless** [comment]
Version updated to 1.2.0

**Comment by rpottsoh** [comment]
This should be squashed when it is merged.

**Comment by cmccandless** [comment]
@rpottsoh Would it be easier for me to go ahead and squash, or is there a simple way to do that from GitHub? I don't have much experience merging pull requests from command line, and that's mostly what I use.

**Comment by petertseng** [comment]
> Would it be easier for me to go ahead and squash, or is there a simple way to do that from GitHub?

You may squash via the command line if you like. Or you may leave it, and the one who *merges* the PR will squash, since GitHub provides the way to do so. I haven't yet seen a way that GitHub provides the *submitter* of the PR to squash via web, so if you want to do it you will be doing it via the command line.

You are welcome do to so, or not, as you please.

**Comment by cmccandless** [comment]
If there's an easy way for the merger to squash, I'll leave it alone.

⁣


Corey McCandless​

**Comment by Insti** [comment]
Squashed and merged, thanks @cmccandless :heart:

**Pull request merged**
