### PR TITLE
Isogram: test a string containing digits

### PR DESCRIPTION
**Pull request by elyashiv**
I actually had a solution submitted with a bug in this area (out of bounds of an array).

### CODE REVIEW

**Comment by rpottsoh** [comment]
I guess I am not for or against this change, but wonder if it might be better to update [decription.md](https://github.com/exercism/problem-specifications/blob/c514bf3bd0/exercises/isogram/description.md) to contain another example of an acceptable isogram instead of adding a test?

for example:
Examples of isograms:

- lumberjacks
- background
- downstream
- six-year-old

could become:

Examples of isograms:

- lumberjacks
- background
- downstream
- six-year-old
- 123123abc

I suppose it could _also_ be acceptable to change description.md as well.   I'm just thinking out loud....

**Comment by elyashiv** [comment]
I think that there should be a test for every case, but I do agree that this should be mentioned in the description. I updated the PR.

**Comment by sshine** [comment]
I don't think this test adds value to the exercise. Numbers only become a corner-case by extending the test to expect them.

I would rather not see input sanitization become a mandatory part of every string-related exercise, but rather have tracks make this choice depending on how the exercise is used.

**Comment by rpottsoh** [comment]
Do we have issues with the clarification added to description.md or are we opposed to all of the proposed changes?  I remain on the fence.

**Comment by sshine** [comment]
Before the addition of digits, the assignment works on the subset `[A-Za-z -]` with `[ -]` being "ignore characters". Little is gained by extending this set arbitrarily but not completely.

@elyashiv: Could this bug be triggered by excessive occurrence of `[ -]`?

**Comment by ErikSchierboom** [comment]
> Little is gained by extending this set arbitrarily but not completely: You make the exercise longer but not harder.

I agree with this sentiment.

**Comment by kotp** [comment]
Closing as indicated in comments by @bitfield and @elyashiv .

**Pull request closed without merging**
