### PR TITLE
alphametics: Update json for new "input" policy

### PR DESCRIPTION
**Pull request by Stargator**
#996 Updated the schema for canonical data. So I am updating the exercise's json to reflect the change.

### CODE REVIEW

**Comment by rpottsoh** [comment]
Should be OK to merge unless you are waiting on #1024 .  #1024 needs to bump the version, which will affect your version....

**Comment by Stargator** [comment]
@rpottsoh I'm fine with waiting until #1024 is done and I'll go ahead and bump my version as anticipated.

**Comment by Stargator** [comment]
Updated to reflect recent changes

**Comment by rpottsoh** [comment]
@ErikSchierboom I have managed to rebasae....

**Comment by ErikSchierboom** [comment]
@rpottsoh @Stargator Thanks for this!

**Pull request merged**
