### PR TITLE
fix typo for bash raindrops exercise

### PR DESCRIPTION
**Pull request by khendrikse**
I saw this little error while doing the exercise. I am hoping this reads a bit easier!

Going from:
`The simplest way to test if a one number is a factor of another is`

to 

`The simplest way to test if one number is a factor of another is`

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]

**Comment by SleeplessByte** [comment]
cc @exercism/reviewers

**Review by neenjaw — APPROVED** [review]

**Review by BethanyG — APPROVED** [review]

**Comment by glennj** [comment]
OK, now what has to happen so the change is reflected in each track?

**Comment by BethanyG** [comment]
@glennj  -- I think its a `configlet` thing.  But the docs are [sparse](https://github.com/exercism/docs/blob/main/building/configlet/generating-documents.md)  @SleeplessByte -- any insight into the syncing action?

**Comment by angelikatyborska** [comment]
Once https://github.com/exercism/configlet/issues/179 gets implemented, track maintainers will be able to automatically update their tracks so that the practice exercises all have up to date instructions. Otherwise it's not possible at the moment, not without @ErikSchierboom running a script that would do this.

It happened once this year for all exercises with Erik's script.

**Comment by SleeplessByte** [comment]
Until then, track maintainers can manually update using configlet sync (or generate).

**Comment by ErikSchierboom** [comment]
We (well @ee7) are indeed working on adding this functionality. We hope to be releasing this sometime soon-ish.

**Pull request merged**
