### PR TITLE
Revert "Revert "Knapsack: Make Bob a Sherpa""

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Reverts exercism/problem-specifications#2472

Sorry about all this!

### CODE REVIEW

**Comment by IsaacG** [comment]
The icon issue has been resolved.

**Comment by ErikSchierboom** [comment]
I'm still seeing the old icon when I view https://assets.exercism.org/exercises/knapsack.svg @IsaacG do you see the new one?

**Comment by IsaacG** [comment]
> I'm still seeing the old icon when I view https://assets.exercism.org/exercises/knapsack.svg @IsaacG do you see the new one?

I'm seeing the old one. Should !181 be reopened?

**Comment by ErikSchierboom** [comment]
It's a cache invalidation issue. It's weird, because it _should_ be invalidated:

```
{
    "Location": "https://cloudfront.amazonaws.com/2020-05-31/distribution/E2UP4JZ9NOWLGP/invalidation/I3NIWLRGKIS3WUJE5UAXQBMPUY",
    "Invalidation": {
        "Id": "I3NIWLRGKIS3WUJE5UAXQBMPUY",
        "Status": "InProgress",
        "CreateTime": "2024-09-05T06:11:42.471000+00:00",
        "InvalidationBatch": {
            "Paths": {
                "Quantity": 1,
                "Items": [
                    "/exercises/knapsack.svg"
                ]
            },
            "CallerReference": "cli-17255[16](https://github.com/exercism/website-icons/actions/runs/10714872114/job/29709310703#step:7:17)702-237545"
        }
    }
}
```

as per https://github.com/exercism/website-icons/actions/runs/10714872114/job/29709310703

**Comment by ErikSchierboom** [comment]
I've tried manually running the invalidation, but it doesn't seem to work: https://assets.exercism.org/exercises/knapsack.svg

**Comment by ErikSchierboom** [comment]
I'll let @iHiD look into this when he has time.

**Comment by Cool-Katt** [comment]
I know this is an old issue but I just checked and the new icon is showing on the site, so I suppose this can be closed. 
Also, the text is unchanged so it still has references to Bob being a thief. @ErikSchierboom

**Pull request merged**
