### PR TITLE
Normalizes topics to snake_case notation

### PR DESCRIPTION
**Pull request by m-a-ge**
This is meant to normalize topics to snake_case notation as discussed earlier.

Also relates to #888 

Your feedback is welcomed

### CODE REVIEW

**Comment by tleen** [comment]
Lately it seems to be good practice to keep .txt documents compatible with markdown. As that was the case in the original file, I would recommend keeping the previous header style and limiting this PR to the snake casing.

This will also conflict with #888 (and potentially #886), should probably wait for #888 to be merged in, fix conflicts then this one would be good to go.

**Comment by m-a-ge** [comment]
@tleen, got it, thanks

**Comment by tleen** [comment]
#888 is in :+1: snake_case that into this and we should be good to go!

**Comment by m-a-ge** [comment]
@tleen, PR has been updated accordingly

**Pull request merged**
