### PR TITLE
Remove version

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Note: I'm aware that this PR will break some existing tools (like test generators). We'll post an issue on each track once we're re-opening this repo making people aware of the changes.

### CODE REVIEW

**Comment by iHiD** [comment]
@ErikSchierboom What will this break in this intermediate stage? (e.g. the maintainers dashboard)

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom What will this break in this intermediate stage? (e.g. the maintainers dashboard)

The maintainers dashboard will indeed break, as will tools that use the version (most likely: test generators).

**Comment by Stargator** [comment]
@ErikSchierboom Why was this done? I liked having versions for the v2 exercises. Helped to keep up to date on changes especially now that this repo is reopened.

I also would have expected v3 concepts and practice exercises to have a similar version parameter.

**Comment by SaschaMann** [comment]
> Why was this done? I ask because I don't see a conversation that discussed this.

https://github.com/exercism/problem-specifications/issues/1674

**Comment by ErikSchierboom** [comment]
Thanks for providing the link @SaschaMann! Let me know if that clears things up for you @Stargator.

**Comment by Stargator** [comment]
@ErikSchierboom That helps, thanks.

**Comment by anowereng** [comment]
zxx

**Pull request merged**
