### PR TITLE
Clarify given range defines factors not product

### PR DESCRIPTION
**Pull request by stevensonmt**
Also fix `it's` vs `its` typos.

### CODE REVIEW

**Comment by petertseng** [comment]
The guidelines at https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/pull-request-guidelines.md request that the exercise should go in the first line of the commit message(s).

As evidenced by the fact that this commit message says "also", the commit is doing two completely separate things (1. clarify the range defines the factors 2. it's -> its) and thus it should be two separate commits.

The counterpoint to my argument is that we are highly unlikely to ever bisect this repo nor revert either of the two resulting commits. OK, if you buy the counterargument, I promise I will not complain if it is merged as is. I was simply obligated to point it out.

**Comment by petertseng** [comment]
EBWODP: In addition to my previous comment which suggests things to change, I also say:

This is a good modification to the problem specification. Thanks for doing it.

**Comment by stevensonmt** [comment]
Point taken @petertseng.  I didn't think the `its` vs `it's` corrections warranted a separate PR, though technically perhaps it should have been.

**Comment by petertseng** [comment]
Separate PR not necessarily needed; two commits in same PR would make sense

**Pull request merged**
