### PR TITLE
topics.txt: fix typo "parallellism"

### PR DESCRIPTION
**Pull request by rahulagrawal97**

### CODE REVIEW

**Comment by Insti** [comment]
@rahulagrawal97 Thanks, it's more useful to know *what* the change is rather than *where*

So a better topic may be: 

topics.txt: Fix typo "parallellism"

There's also an unnecessary whitespace change on the last line.

**Comment by rahulagrawal97** [comment]
@Insti Thanks a lot for letting me know!
This is my first PR, so you see any feedback helps.
also it'd be great if you could add the hacktoberfest label.

**Comment by Insti** [comment]
Thanks @rahulagrawal97, welcome!
I've added the Hactoberfest label, but Hacktoberfest will detect all pull requests, even those without the label.

The whitespace change at the end is tricky, it's probably due to your editor removing the newline from the end of the file. If you used the Github editor to make the change you probably cannot do anything about that.

**Comment by Insti** [comment]
Thanks @rahulagrawal97 I hope you get your t-shirt!

**Pull request merged**
