### PR TITLE
Create canonical-data.json

### PR DESCRIPTION
**Pull request by sergioea**

### CODE REVIEW

**Comment by petertseng** [comment]
Because the three files from #858 #859 #860 must be present in the repo at the same time, it seems like it would be better to have it be one PR instead of three separate. Please let us know if there is a reason it must be three separate PRs. It will not make much sense to review it while it is three separate PRs.

**Comment by rpottsoh** [comment]
@sergioea 

Thanks for taking the time to propose a new exercise!  It would also be helpful if the title of the single PR contained a blurb that it was a new exercise proposal and the name of the proposed exercise.

As @petertseng stated, the three files, that define an exercise, should be contained within a single PR so that Travis CI can check it.

Let us know if you are unsure how to proceed.  We're happy to help!

**Comment by ErikSchierboom** [comment]
@sergioea Are you still interested in submitting this PR? If so, could you perhaps resubmit it in the format suggested by @rpottsoh . Thanks.

**Comment by ErikSchierboom** [comment]
@sergioea I'm gonna go ahead and close this PR. Feel free to open a new PR when you are ready to work on this again!

**Pull request closed without merging**
