### PR TITLE
README.md: Add instruction for exercise glyph creation

### LINKED ISSUE #1271: README.md: should have a statement regarding informing design team when a new glyph is needed for a new exercise
When creating a new exercise the design team needs to be informed that there is a need for a new glyph for the new exercise.

@iHiD said in exercism/website-icons#7:
> ...when a new exercises is added to specifications, a new issue should be opened here to inform the design team that a new icon needs designing. Any suggestions or examples in that issue will be appreciated too.

Task to be completed:
The README for this repo should have a statement added to document the need for this new measure to be taken when creating a new exercise.

When a new issue is opened in exercism/website-icons it should make a reference to the new exercise's PR that is slated to be merged or was recently merged.  Having easy access to the new exercise documentation could be useful during the design of a new glyph.

### PR DESCRIPTION
**Pull request by rpottsoh**
closes #1271

### CODE REVIEW

**Comment by rpottsoh** [comment]
Apparently the file had line feeds at the end of each line and not crlf's.....  I am going to try and fix this so I am only changing what I am setting out to change in this file.....

**Comment by cmccandless** [comment]
Note: while this should help cover future exercises, `high-scores` and `dnd-character` were implemented without glyphs and still need them.

**Comment by sshine** [comment]
I forgot this part!

Can we make a build hook fail in problem-specifications if a glyph is not there yet?

**Comment by rpottsoh** [comment]
I believe `high-scores` has a glyph. I'm on my phone so don't have access to git you the sha of the commit from website-icons.

**Comment by rpottsoh** [comment]
The glyph has nothing to do with the exercise specification so I think should not factor into the behavior of this repo.  

I would agree that perhaps the site should not make an exercise available to students if there is no glyph file associated with it.

**Comment by petertseng** [comment]
> I would agree that perhaps the site should not make an exercise available to students if there is no glyph file associated with it.

Please prepare my below comment for the time when this gets proposed. Until then, my below comment is not relevant for this issue (consider hiding it):

Ah, the glyphs is going to have their work cut out for them, then, since they're going to have to create some glyphs for the track-specific exercises as well.

coq: ["tautology"]
ballerina: ["hello-world-service", "greeting-service", "service-invocation", "legacy-service-client", "calculator-service", "order-management", "service-composition", "echo-world-service"]
rust: ["luhn-from", "luhn-trait", "macros", "decimal"]
groovy: ["double-linked-list"]

**Pull request merged**
