### PR TITLE
phone-number: invalid when 12 digits and starting with "1" "1"

### PR DESCRIPTION
**Pull request by sshine**
This should catch solutions with a validation function that calls itself recursively when the first digit is '1'.

### CODE REVIEW

**Comment by rpottsoh** [comment]
@sshine I like this change you've made.  #1320 would like to make more changes that are very similar to what you have done so far.  Would you be willing to make a few more changes?  Please don't feel obligated.

**Comment by sshine** [comment]
I encountered this one because of a bug in my own first solution. "Solving for 11 digits is like checking for '1' and solving for 10 digits!" Except I actually checked for N digits as long as the first N-10 digits were '1's, heh.)

**Comment by rpottsoh** [comment]
@sshine it has been 4 days....  I am going to close this PR in favor of #1327.  Thanks for your efforts.

**Comment by sshine** [comment]
How about a comment that this is non-mandatory for such powerful languages? Surely the vast majority of languages use strings. Even Haskell.

**Comment by sshine** [comment]
It doesn't have a 12-digit number that begins with two 1s. This test catches when the preceding 1 is stripped recursively and what remains is a valid 10-digit number because more than one 1 is eaten.

**Comment by sshine** [comment]
I retract that as I didn't look careful enough.

The 11-digit test you describe is sufficient.

**Pull request closed without merging**
