### PR TITLE
dnd-character: Add title to metadata

### PR DESCRIPTION
**Pull request by sshine**
Currently, the exercise shows up as 'Dnd Character' when 'DND Character' would be more appropriate.

I don't need to bump any version number for this change, right?

### CODE REVIEW

**Comment by cmccandless** [comment]
> I'll let you decide this, but you may find that DnD is more common than DND.

What about 'D&D'?

**Comment by sshine** [comment]
'D&D' is even better, but I wasn't sure if it'd work in all circumstances, '&' being a scary character on the internet.

**Comment by sshine** [comment]
Also, I haven't played DnD / D&D since 1st edition when I was 11, so I'm no authority any more. :-D

**Comment by cmccandless** [comment]
> but I wasn't sure if it'd work in all circumstances, '&' being a scary character on the internet.

That's... a really good point. I guess we'll find out if that breaks anything on the site.

**Pull request merged**
