### PR TITLE
high-scores: multiple improvements

### PR DESCRIPTION
**Pull request by F3PiX**
These updates address issues that were raised after the first implementation (#1378 )

### CODE REVIEW

**Comment by rpottsoh** [comment]
Are there any issues or PRs that document the impetus behind these changes?

**Comment by F3PiX** [comment]
@rpottsoh I know for sure that the naming things came up in discussions about the initial implementation here and in the Ruby track, but I couldn't pinpoint them.

The comment added is a solution for the fact that the important information of the goal of the exercise is buried in the Ruby Track hint.md, and I feel that that kind of information needs to be available to the maintainers. To make it easier if and how the exercise fits in their tracks.

**Comment by rpottsoh** [comment]
I see.  I just wanted to make sure there wasn't something that should be documented here because of how the initial comment is worded.
> These updates address issues that were raised after the first implementation

I am fine with the changes, they seem reasonable.  I just was not understanding why they were needed.  :smile:

**Comment by F3PiX** [comment]
> I just was not understanding why they were needed. 😄

You're right, I should've documented it better, but honestly, I lost track of them.  😱 😜 
Thanks!

**Comment by F3PiX** [comment]
Thanks @ErikSchierboom , @rpottsoh !! 
cc @pgaspar

**Pull request merged**
