### PR TITLE
Add reimplements to schema

### PR DESCRIPTION
**Pull request by SaschaMann**
(view the commits separately for a more readable diff)

### CODE REVIEW

**Comment by SaschaMann** [comment]
See #1704 for an example that this fixes the build failures in #1691.

**Review by petertseng — APPROVED** [review]

**Comment by SaschaMann** [comment]
Thanks for the really quick reviews @petertseng :)

**Review by ee7 — APPROVED** [review]
I approve on the basis that CI now passes for a `canonical-data.json` that contains `reimplements`.

But two questions:
1) Do we have an official ordering that the keys are supposed to be in?
2) If so, should we enforce the key order during CI? Maybe it helps with readability when adding tests. The ordering seemed pretty consistent before, but  there will be nearly double the number of keys now.


I notice that the `reimplements` in this PR is after `uuid`, but when I made my recent PRs I instead ordered the keys as I saw them in https://github.com/exercism/problem-specifications/issues/1674, that is:
```json
  {
    "uuid": "82d32c2e-07b5-42d9-9b1c-19af72bae860",
    "description": "two times one is two",
    "comments": ["Expected value is changed to 2"],
    "reimplements": "e46c542b-31fc-4506-bcae-6b62b3268537",
    "property": "twice",
    "input": {
      "number": 1
    },
    "expected": 2
  }
```

**Comment by iHiD** [comment]
We should do, and we should enforce it, yes. Can whoever merges this (or anyone before), please create an issue about deciding order, and another about CI enforcing?

**Comment by ErikSchierboom** [comment]
> We should do, and we should enforce it, yes. Can whoever merges this (or anyone before), please create an issue about deciding order, and another about CI enforcing?

This is also planned for when we update configlet with the sync functionality BTW.

**Comment by ErikSchierboom** [comment]
Thanks for the quick fix @SaschaMann!

**Pull request merged**
