### PR TITLE
robot-simulator: encode position as object instead of string

### LINKED ISSUE #722: robot-simulator: should represent positions as array or object, not string
Currently, positions are represented as strings like `"(11, 5)"` in the [canonical data for robot-simulator](https://github.com/exercism/x-common/blob/master/exercises/robot-simulator/canonical-data.json).

For languages where `(11, 5)` is valid syntax, this seems fine - the test generator will simply be able to interpolate this string wherever it is necessary.

For those languages where it is not valid syntax, it seems like an unusual burden to force test generators for that language to parse the x and y coordinate from the string `"(11, 5)"`.

Consider changing this to an array containing two integers such as `[11, 5]` or an object with explicit keys such as `{"x": 11, "y": 5}`.

### PR DESCRIPTION
**Pull request by HarrisonMc555**
Closes #722.

I decided to use objects. Some people preferred arrays and some people preferred objects, but it seems like in other problems objects were preferred because they were more explicit (see #721). I don't believe we have a policy yet on whether to use arrays or objects for things like this, but I believe that objects would be a better decision. There are some situations in which it doesn't really matter and some people would prefer arrays, but there are some situations where it really would be better to have objects. Since it sometimes is desirable to have objects and only sometimes slightly preferred to have arrays, I think objects are a better default policy.

### CODE REVIEW

**Comment by stkent** [comment]
Nice change! Please also bump the canonical data version as appropriate: https://github.com/exercism/problem-specifications#test-data-versioning :)

**Comment by HarrisonMc555** [comment]
Thanks, bumped major number.

**Comment by NobbZ** [comment]
Since I can't alter my review… Of course I like the overal change, since it is much more clear how the coordinates have to be read.

Also I do clearly prefer objects over arrays/lists here for the representation of the testdata, since `{"x": 1, "y": 2}` is so much more obvoius than `[1, 2]`. To be honest, there were not much of a semantic difference between `[1, 2]` ans `"(1, 2)"`…

**Comment by Insti** [comment]
> So version should in my opinion only get bumped to 1.0.1.

I think I agree with this.

**Comment by Insti** [comment]
@NobbZ do you want to make an issue for this discussion? I think it's worth having but we seem to be having this discussion across 3 different PRs. It would be good to have it all in one place we can tag as `policy` at some point.

**Comment by NobbZ** [comment]
Yeah, I was going to do so, but first I had to remove false negatives to not block the process of merging.

**Comment by HarrisonMc555** [comment]
Hey sorry I missed the party. I think I was supposed to squash but didn't get around to it in time. Thanks everyone!

**Pull request merged**
