### PR TITLE
simple-cipher: remove checks for invalid input

### PR DESCRIPTION
**Pull request by rpottsoh**
- Mention of invalid input removed from README.
- Removed cases that test for invalid input.

These changes follow on the discussion that has taken place in  #902 and #523.  There may be some other examples regarding the discussion that I am missing.  Feel free to point them out.

This PR is intended to be an alternate solution to #1298 to replace #1316.

### CODE REVIEW

**Comment by Insti** [comment]
I like this change.

Perhaps we (@xarxziux?) can make a new exercise called 'key-validation' or something that combines these tests with the tests that they added in #1346 since string validation is still an important thing to learn.

**Comment by xarxziux** [comment]
Do you mean an advanced version of this exercise (not-so-simple-cipher?), or an entirely separate exercise that only performs general data validation?

I think having a tiered version of these kind of exercises would be good in principle - whether that is in the form of a separate, more advanced exercise, or optional test cases.  I'm just not sure that the format of this site really supports either.  Is there an accepted way to declare optional or advanced test cases in the spec?

**Comment by rpottsoh** [comment]
A new exercise could be a side exercise and it would either require that the student have already completed this exercise in order to have the code necessary for ciphering or the new exercise could provide a stub that contained code for ciphering.  The student would be tasked with writing the code to protect the ciphering logic from bad input.  If the ciphering logic is provided then the new exercise would be independent of this exercise...  I am not sure which way is the best to go.

**Comment by xarxziux** [comment]
On another coding site, Codewars, there are a number of exercises that form a series.  You first take on a relatively easy problem.  Once you've solved that, then there's a more difficult version so solve and so on.  This site doesn't really have that concept, but maybe it would not be a bad idea to do something like that.

The description on this exercise already has three stages.  If we are making the requirements easier, instead of making the unit tests harder, maybe we should look at serialising the exercise.  Instead of steps 1 to 3, split it into two or three separate exercises with increasing difficulty.  I'm not sure there's enough material in the current exercise to warrant three exercises, but I'm sure there are extra complexities and restrictions that can be made on the final stage to make it work.

**Comment by rpottsoh** [comment]
I am not opposed to this idea.  I have already been thinking about it for a
new exercise specific to the Delphi track.  The exercise is for writing a
calculator.  The first half of the exercise will deal with the business
logic of dealing with performing the calculations; handled in a class....
The follow on exercise will see the student creating a UI to interface with
the class they wrote in the previous exercise.  This allows the student a
chance to work with Delphi's nice UI creation capabilities while at the
same time promoting loose coupling between the business logic on the UI.  I
have not worked on this in MANY months.  The idea could certainly be
applied to other tracks.

**Comment by Insti** [comment]
I meant an entirely new and separate exercise that just performs data validation.

It should work standalone, but would be ok if it is part of a series.

**Pull request merged**
