### PR TITLE
robot-simulator: apply "input" policy

### PR DESCRIPTION
**Pull request by rpottsoh**
per #996

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
> I would consider it acceptable to have position and direction be properties of input, and remove the robot altogether.

I think I agree. This is also already the case for some of the `expected` values.

**Comment by rpottsoh** [comment]
@petertseng lately as I have been applying #996 to exercise testdata I have been receiving an email from Travis CI letting me know the status of the checks it has made.  This is a recent behavior that I have noticed.  I am not sure if I like it or not.  I wanted to point out that for the second commit of this PR I did not receive an email from Travis CI.  Should I be expecting an email for every commit or just this first?  Should I even be receiving email from Travis CI?  I apologize in advance if you are not the person to whose attention I should bring this to.

**Comment by petertseng** [comment]
I have no idea about Travis. Apology accepted.

**Comment by petertseng** [comment]
I'm going to guess you're getting emails because you are making your branches on Exercism's copy of the repo, instead of on your fork. In that case, I have observed getting an email on:

* First time the branch is created
* State transition from pass to fail
* State transition from fail to fail
* State transition from fail to pass

I have observed not getting an email on:

* State transition from pass to pass

I have not yet discovered a way to change Travis's behaviour in this regard. Either way, since making branch on Exercism's copy of the repo is behaviour that I do not condone (https://github.com/exercism/discussions/issues/174#issuecomment-331231646), I can be of no further help in this matter. If you wish not to receive emails, disable Travis CI for your fork and then make branches on your fork.

**Comment by petertseng** [comment]
EBWODP

> disable Travis CI for your fork and then make branches on your fork.

I can't even be sure this will work. Editing my post to sound less sure of myself.

**Comment by rpottsoh** [comment]
@petertseng your guess is correct.  I was preparing a different comment, but had to break for lunch, since then your comment came in that sums up my observation exactly.  

When I create a branch off of exercism/master from which I submit a PR, Travis performs 2 checks.  If I submit the PR from a branch off of my fork Travis only performs one check.  I do not receive an email from Travis for the PR that originates from my fork so I have determined that the `continuous-integration/travis-ci/push` check is triggering the email because this check is not performed for PRs that do not originate from a branch off of exercism/master.

regarding receiving email, if I simply go back to submitting PRs from my fork the emails will cease.  I am left wondering why sometimes 2 checks are made vs. 1.

**Comment by petertseng** [comment]
> 2 checks are made vs. 1.

One build for every PR made to exercism, regardless of whether it is on a fork: https://travis-ci.org/exercism/problem-specifications/pull_requests

One build for every branch on exercism's copy of the repo (and therefore by definition not on any forks): https://travis-ci.org/exercism/problem-specifications/branches

**Comment by petertseng** [comment]
EBWODP:

> regardless of whether it is on a fork

unclear "it". I'll go with "the branch backing the PR"

**Comment by petertseng** [comment]
EBWODP:

Incorporate https://travis-ci.org/exercism/problem-specifications/settings into my explanation, because "Build pushed branches" and "Build pushed pull branches" are on.

**Comment by petertseng** [comment]
EBWODP

Any PR backed by a branch on exercism's copy of the repo thus gets two builds, as a logical consequence.

**Comment by rpottsoh** [comment]
Correct assumption of "it".  Thanks for all the insight and feedback
@petertseng.

**Comment by petertseng** [comment]
`instructions` is an `input`, but it was not moved to the `input` object.

**Comment by rpottsoh** [comment]
> instructions is an input, but it was not moved to the input object.

Oops.  Thanks for catching that @petertseng.  I'll take care of it.

**Pull request merged**
