### PR TITLE
Remove unneeded nesting

### PR DESCRIPTION
**Pull request by ErikSchierboom**
The canonical data for `isogram` and `prime-factors` contain nesting, but as there is only one level of nesting, this does not add any value.﻿

This can break test generators, but as everything is still in flux anyway, I think this is a good time to do this.

Note: please don't squash merge to retain the individual commits

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]
Yeah, I mentioned this when updating JS to spec. Agreed that THIS is the best time to do this.

**Comment by ee7** [comment]
I think there are many more exercises for which we'd have to make the same change. Here is an incomplete list:
- [`alphametics`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/alphametics/canonical-data.json)
- [`book-store`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/book-store/canonical-data.json)
- [`etl`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/etl/canonical-data.json)
- [`gigasecond`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/gigasecond/canonical-data.json)
- [`nucleotide-count`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/nucleotide-count/canonical-data.json)
- [`ocr-numbers`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/ocr-numbers/canonical-data.json)
- [`pascals-triangle`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/pascals-triangle/canonical-data.json)
- [`phone-number`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/phone-number/canonical-data.json)
- [`protein-translation`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/protein-translation/canonical-data.json)
- [`rotational-cipher`](https://github.com/exercism/problem-specifications/blob/4ab6ff38e4f3e96be2160360e30c606e94fdb5b6/exercises/rotational-cipher/canonical-data.json)

**Comment by ErikSchierboom** [comment]
I'd like to get all those fixed in this PR too. I'll take a little time to find all of them.

**Comment by ee7** [comment]
See previous discussion: https://github.com/exercism/problem-specifications/issues/1671

**Review by SaschaMann — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
I think the following bash script finds all these unneeded nesting exercises:

> find . -name canonical-data.json -exec jq '. | select(.cases | length == 1) | select(.cases[] | .cases != null) | .exercise' {} \; | uniq | sort

This outputs:

```
"acronym"
"alphametics"
"book-store"
"etl"
"food-chain"
"gigasecond"
"house"
"micro-blog"
"nucleotide-count"
"ocr-numbers"
"pascals-triangle"
"phone-number"
"protein-translation"
"rotational-cipher"
"secret-handshake"
"trinary"
```

**Comment by ErikSchierboom** [comment]
I found 18 exercises for which there was unneeded nesting, which I've removed in this PR. Each exercise has its own commit to make reviewing easier.

**Review by wolf99 — APPROVED** [review]

**Review by SleeplessByte — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
> Are there any canonical-data.json files with 3 levels of cases that could be 2?

No idea. It's less likely, but I'll check next week.

> Do we have a list of tracks that use generators so that we can let some maintainers know?

Nope, unfortunately we don't.

**Comment by BethanyG** [comment]
Just discovered that it broke Python.  Took me a while to figure out what was going on, but glad I found this issue.  Working on it now.  😆

**Pull request merged**
