### PR TITLE
change: add simplest test case

### PR DESCRIPTION
**Pull request by SleeplessByte**
In JavaScript we've had this testcase to kick-off the exercise, input and output, without needing to write an actual algorithm. Adding it here for completeness.

### CODE REVIEW

**Review by SaschaMann — APPROVED** [review]
LGTM. For better readability of the commit history, I'd prefer if you could split the test addition and the formatting to two commits and then rebase them.

**Comment by SleeplessByte** [comment]
I'm unwilling to turn of editor formatting. It really breaks up the workflow where I am editing the track(s) in one window and the tests in another. What I could do is "just save it first", commit that, and then make my addition in a separate commit. Would it suffice?

If yes, I'll do that going forward.

**Comment by SaschaMann** [comment]
> What I could do is "just save it first", commit that, and then make my addition in a separate commit. Would it suffice?

Yeah that's fine. Order doesn't matter but if for whatever reason we need to find something in the commit history, mashing formatting with content changes makes it harder.

(Perhaps we should setup the everloved prettier actions here too :D )

**Comment by SleeplessByte** [comment]
Understood! Fixed behaviour in new PRs :)

**Comment by ErikSchierboom** [comment]
> (Perhaps we should setup the everloved prettier actions here too :D )

I think that for this repo we could even go as far as automatically applying prettier :)

**Review by ErikSchierboom — APPROVED** [review]
> LGTM. For better readability of the commit history, I'd prefer if you could split the test addition and the formatting to two commits and then rebase them.

I agree with this. It is slightly inconvenient to figure out what exactly was added and what was reformatted. 

Good addition!

**Review by valentin-p — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks @SleeplessByte!

**Pull request merged**
