### PR TITLE
Add error scenario

### PR DESCRIPTION
**Pull request by ErikSchierboom**
When working with canonical data, I often found that one of the first criteria for me to decide whether I want a test case to be implemented is whether it does error handling. In some cases, error handling fits the exercise well, in others less so. While one _can_ figure this out by looking at the structure of the `expected` value, it might be convenient to also add a scenario to these error test cases to allow for easy filtering. Let me know what you think.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Maybe we want to differentiate between input validation and runtime validation. Tracks often make different choices based on where the validation takes place.

But a generic error scenario would be fine with me too.

**Comment by ErikSchierboom** [comment]
Sounds like a good idea. Suggestions for proper names?

**Review by ErikSchierboom — COMMENTED** [review]
@SleeplessByte What do you think about the latest version?

**Comment by SleeplessByte** [comment]
Fine with me :)

**Comment by ErikSchierboom** [comment]
Great. Then I just need three approvals :)

**Review by SleeplessByte — APPROVED** [review]

**Review by SleeplessByte — CHANGES_REQUESTED** [review]
This is missing the changes to schema.

**Comment by ErikSchierboom** [comment]
To prevent us from making this mistake in the future, I've created https://github.com/exercism/problem-specifications/pull/1765

**Review by wolf99 — APPROVED** [review]

**Review by SleeplessByte — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Could someone from @exercism/reviewers look at this PR?

**Review by ee7 — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
