### PR TITLE
CI: Add /rebase command

### PR DESCRIPTION
**Pull request by SaschaMann**
(stolen from v3 repo)

### CODE REVIEW

**Comment by iHiD** [comment]
This won't run on forks, right?

**Comment by SaschaMann** [comment]
Nope, as usual. But it'll still help people with commit access (e.g. when required checks change ;)

**Review by ErikSchierboom — APPROVED** [review]
We should probably also document that this is possible somewhere. This can be done later.

**Review by SleeplessByte — APPROVED** [review]

**Review by iHiD — APPROVED** [review]

**Comment by ynfle** [comment]
There is also [autorebase](https://github.com/tibdex/autorebase) & [autosquash](https://github.com/marketplace/actions/autosquash) which may be useful

**Comment by SaschaMann** [comment]
Thanks!

**Pull request merged**
