### PR TITLE
rectangles: Add test for missing sides

### PR DESCRIPTION
**Pull request by hardselius**
Some solutions to this exercise will look for the top corners of the rectangles, making sure they are connected by a horizontal line, then go on to walk down the left and right side to find corners at the same row, in which case a rectangle is detected. These solutions sometimes fail to check that the bottom two corners are connected by a horizontal line. This test case will catch that.

### CODE REVIEW

**Review by petertseng — APPROVED** [review]
How likely is it that the equivalent case for a missing right side should also be included?

```
+-+
|
+-+
```

(with other surrounding rectangles to make that an actually-valid input)

**Comment by hardselius** [comment]
@petertseng I'm not sure. I suppose someone would try search columns first and then go from left to right, but it certainly seems less likely than top to bottom. Maybe it could test something like

```
+-+ +-+
| | | |
+-+-+-+
  | |  
+-+-+-+
| | | |
+-+ +-+
```

to cover all scenarios?

**Comment by hardselius** [comment]
I changed this to test all scenarios instead.

**Review by petertseng — APPROVED** [review]

**Review by jiegillet — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks @hardselius! 🎉

**Pull request merged**
