### PR TITLE
alphametics: Update test description

### PR DESCRIPTION
**Pull request by nikamirrr**
The test contains 199 addends, not 41. Sorry

### CODE REVIEW

**Comment by petertseng** [comment]
Yup.

Please prefix commit message and PR description with "alphametics:"

I would like to take this without changing version since this is something that should have happened with 1.1.0

However I guess there is a possibility that someone could have used 1.1.0 to generate. I could check all the repos to see whether anyone in fact did so, but lazy.

So, I think we have to have version 1.1.1, unless there is more agreement that staying 1.1.0 is OK. I don't care either way but if I don't hear from anyone else I'm going to ask 1.1.1.

**Comment by rpottsoh** [comment]
I think to be PC the version should be bumped.

**Comment by nikamirrr** [comment]
Like this?
 "version": "1.1.0" ->  "version": "1.1.1",

**Comment by ErikSchierboom** [comment]
@nikamirrr Yes, precisely!

**Comment by ErikSchierboom** [comment]
Thanks @nikamirrr!

**Comment by nikamirrr** [comment]
Absolutely! Thank you, I am not a pro developer, and this is the opportunity for me to get more familiar with github and such.

**Pull request merged**
