### PR TITLE
Remove topics.txt

### LINKED ISSUE #1894: Remove TOPICS.txt
This repository contains a [TOPICS.txt file](https://github.com/exercism/problem-specifications/blob/main/TOPICS.txt) which was useful for Exercism v2, as exercises could have a list of topics. However, with Exercism v3 being released, topics are no longer used and the purpose of the TOPICS.txt as a central point of reference seems to be nil. I suggest to remove the file. Are there any objections to that?

One side note: we _could_ consider having a list of concepts on a docs page that is inspired by this list. For inspiration for tracks when working out concepts.

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Exercism v3 has deprecated topics, so there is no use of the topics.txt file anymore

I've made this a draft because the publishing of the updated tracks maintenance dashboard is failing: https://github.com/exercism/tracks-maintenance-dashboard/runs/5063440739?check_suite_focus=true

Closes #1894

### CODE REVIEW

**Review by kotp — APPROVED** [review]

**Review by petertseng — APPROVED** [review]

**Comment by SleeplessByte** [comment]
@ErikSchierboom It's failing because the `InvalidAccessKeyId` (key has likely been revoked or rotated).

**Review by angelikatyborska — APPROVED** [review]

**Review by SaschaMann — APPROVED** [review]

**Comment by SaschaMann** [comment]
Is this ready to be merged?

**Comment by ErikSchierboom** [comment]
No, this is still pending on the track maintenance dashboard not deploying: https://github.com/exercism/tracks-maintenance-dashboard/runs/5063440739?check_suite_focus=true @iHiD could you take a look why that is?

**Comment by kytrinyx** [comment]
@ErikSchierboom This should be good to go now, right?

**Comment by ErikSchierboom** [comment]
@kytrinyx That is correct!

**Pull request merged**
