### PR TITLE
[Secret Handshake] Fix formatting issue in admonition

### PR DESCRIPTION
**Pull request by safwansamsudeen**
There's a note which is looks incorrect in the UI. I think this change will solve it.
image

This is a basic PR, so I have not discussed it in the forum beforehand.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks @safwansamsudeen.

It looks correct to me in the browser on the Ruby track:
Screenshot 2023-06-08 at 1 37 37 PM

Which track are you looking at where it is broken?

**Comment by safwansamsudeen** [comment]
Python - is this perhaps track specific?

**Comment by safwansamsudeen** [comment]
@kytrinyx Nope - it turns out [you've](https://github.com/safwansamsudeen/problem-specifications/commit/a9f93a78db8fb77170d84f07a46c6dae88eda68a) corrected this specifically in Ruby.

**Comment by MatthijsBlom** [comment]
This was fixed in #2238; the patch just hasn't been pulled yet by some tracks.

**Comment by safwansamsudeen** [comment]
@kytrinyx Upon looking around, it seems both Python and JS lack the blank line between the link text and the link url.

You've [committed this](https://github.com/safwansamsudeen/problem-specifications/commit/a9f93a78db8fb77170d84f07a46c6dae88eda68a) only on March 27th - perhaps the tracks haven't synced the change yet?

Sorry for the confusion - I originally [opened this in Python](https://github.com/exercism/python/pull/3436), was redirected here, and then failed to see that there was a blank line difference in this version and Python's.

**Comment by kytrinyx** [comment]
@safwansamsudeen this makes sense. The fix would be to run `bin/configlet-fetch` in the Python and JS repos, and then `bin/configlet sync --update --yes --docs` to update any instructions that have fixes from the upstream. `--metadata`

**Review by SleeplessByte — APPROVED** [review]
Nice.

**Comment by MatthijsBlom** [comment]
@SleeplessByte I actually expect this PR to _break_ the link. See [this forum thread](http://forum.exercism.org/t/link-references-in-special-blocks-admonitions-are-not-rendered/3803/2).

**Review by SleeplessByte — CHANGES_REQUESTED** [review]
Sorry I reviewed the opposite diff which I thought was moving the link inside the admonition.

There is nothing wrong with this markdown and this PR should be closed.

If tracks have broken admonitions, they should sync with the problem specs.

**Comment by SleeplessByte** [comment]
> @SleeplessByte I actually expect this PR to break the rendering in just another way. See [this forum thread](http://forum.exercism.org/t/link-references-in-special-blocks-admonitions-are-not-rendered/3803/2).

Thank you for that. I just rejected this.

I've ran it myself and the old (current) markdown is correct. This PR is invalid.

**Comment by safwansamsudeen** [comment]
Nice to see this understood, thanks to everybody!

**Pull request closed without merging**
