### PR TITLE
Add link checking for markdown in CI

### LINKED ISSUE #2139: Add link checking to CI
#2137 has changed all links to use TLS URLs (i.e. HTTPS).

We should add a link checker with a requirement for HTTPS to be used to ensure this continues and that links are valid in general.

### PR DESCRIPTION
**Pull request by wolf99**
Fixes #2139

### CODE REVIEW

**Review by kytrinyx — APPROVED** [review]
Thank you!

**Comment by wolf99** [comment]
I see a couple of things in the output that I need to adjust for before this is merged

**Comment by wolf99** [comment]
I actually don't know why these warnings are occurring.
The raw files are valid and are not as the checker seems to be interpreting them.
I will look into this further later on.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by jiegillet** [comment]
It's not happy with the email link `[abuse@exercism.org](mailto:abuse@exercism.org?subject=%5BCoC%5D)`

```
## Errors per input
### Errors in CODE_OF_CONDUCT.md
* [file:///home/runner/work/problem-specifications/problem-specifications/mailto:abuse@exercism.org](file:///home/runner/work/problem-specifications/problem-specifications/mailto:abuse@exercism.org): Failed: Cannot find file (status code: ERR)
```

**Comment by Stargator** [comment]
Sorry I am late to the party. The dart track does use lychee for our Link workflow.

We had it disabled a month or so ago because it was failing for mailto links which it should support.

We also use it to enforce https for our links.

**Comment by kytrinyx** [comment]
@Stargator pointed us to the open issue on the lychee repository that is related to the failing mailto check: https://github.com/lycheeverse/lychee/issues/653

**Comment by wolf99** [comment]
This is now correctly failing for a an incorrectly detected bad link (the mailto mentioned by @Stargator ).

Until Lychee fixes that issue and subsequently makes a new release of lychee and the lychee-action, this PR is blocked.

**Comment by mre** [comment]
I've worked on a fix here: https://github.com/lycheeverse/lychee/pull/809.
Some more 👀 would be helpful to get this merged.

**Comment by Stargator** [comment]
@wolf99 @kytrinyx lychee just merged in a fix for this. I anticipate the next version for the lychee-action will include that fix. The dart track has dependabot set to open a PR when that update is available, I believe the same is so for this repo.

**Comment by mre** [comment]
Yup, I'll release a new version soon. Want to merge in https://github.com/lycheeverse/lychee/pull/810 as well.
Thanks for the support on this one y'all. Much appreciated. ❤️

**Comment by wolf99** [comment]
Think you so much for the help @mre !
I have updated the action version in the workflow here and the mailto is no longer failing.

There is still the issue with the timeout for the one link that we have not been able to solve. I will add a commit with an ignore of some sort for this URL.

**Comment by mre** [comment]
No worries.
Just fyi, I also released a new version to fix the issues you described in https://github.com/lycheeverse/lychee-action/issues/169. https://github.com/lycheeverse/lychee-action/releases/tag/v1.5.4
So feel free to update to 1.5.4 to (hopefully) resolve that problem as well.

**Comment by Stargator** [comment]
> No worries.
> Just fyi, I also released a new version to fix the issues you described in https://github.com/lycheeverse/lychee-action/issues/169. https://github.com/lycheeverse/lychee-action/releases/tag/v1.5.4
> So feel free to update to 1.5.4 to (hopefully) resolve that problem as well.

Thanks, @mre!

@wolf99 The check initially failed due to a timeout on one website. I re-ran it and everything is passing. it looks good!

**Review by Stargator — APPROVED** [review]

**Comment by Stargator** [comment]
There is a merge conflict that needs to be resolved

**Comment by wolf99** [comment]
Ill look at this this weekend I hope.

**Comment by wolf99** [comment]
Seems like there are issues with 2 URLs.

1. ✗ [403] https://www.collinsdictionary.com/dictionary/english/lackadaisical | Failed: Network error: Forbidden
2. ⧖ [TIMEOUT] https://papyr.com/hypertextbooks/grammar/ph_noun.htm | Timeout

Testing the first one locally with `curl` returns the same resultunless provided with an *invalid* (contains a `:`) user-agent.
So it seems like it may be an issue with how that site has configured its server?

Testing the second locally with `curl` returns 200; so I am unable to reproduce that issue

**Comment by wolf99** [comment]
Re-ran.
Timeout is gone, but 403 remains.

**Comment by mre** [comment]
Nice. You made some great progress! Thanks for looking into that.
The remaining issue for https://www.collinsdictionary.com/dictionary/english/lackadaisical points towards Cloudflare bot-detection. That's my guess, at least, because they use the same page layout (compare [here](https://community.cloudflare.com/t/just-a-moment-infinite-verifying/477779)). The URL works locally, but on GitHub we seem to trigger the bot detector and there isn't much we can do about it at the moment. lychee does not support JavaScript or cookies. However, you can add a `.lycheeignore` file and add the URL there, to skip it from being tested. That should resolve the issue.

**Comment by wolf99** [comment]
Adding the `.lycheeignore` solved it it seems.

@mre thanks for all your help!

**Comment by kytrinyx** [comment]
Yay, this is looking fantastic. Thanks so much for your work on this @wolf99, and your help with it @mre!

**Pull request merged**
