### PR TITLE
[darts] Add scoreboard image

### PR DESCRIPTION
**Pull request by habere-et-dispertire**
Depends on https://github.com/exercism/images/pull/17

### CODE REVIEW

**Comment by habere-et-dispertire** [comment]
I think the missing file is due to dependency on :

https://github.com/exercism/images/pull/17

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
CC @exercism/reviewers

**Review by kotp — APPROVED** [review]
Very nice.

**Review by kotp — APPROVED** [review]

**Comment by habere-et-dispertire** [comment]
Any more @exercism/reviewers able to review ⛑ ? Much appreciated. 🍭

**Review by IsaacG — APPROVED** [review]

**Comment by habere-et-dispertire** [comment]
Thank you @IsaacG ! 🍦

**Pull request merged**
