### PR TITLE
isogram: Update canonical-data.json as in #919

### PR DESCRIPTION
**Pull request by Selina-Jane**
Changed test description "isogram with duplicated non-letter character" to "isogram with duplicated hyphen", and changed the associated canonical data from "Hjelmqvist-Gryb-Zock-Pfund-Wax" to "six-year-old". This was suggested in issue #919.

### CODE REVIEW

**Comment by rpottsoh** [comment]
:+1:  @Selina-Jane.  Don't forget to update "version"

**Comment by Insti** [comment]
Thanks @Selina-Jane, good point about the version number @rpottsoh.

The version key/value is here: https://github.com/exercism/problem-specifications/pull/920/files#diff-4a2164ce55eed791d3cb1cb39985696aL6

The documentation about version numbers is here: https://github.com/exercism/problem-specifications#major-version-changes

**Comment by Selina-Jane** [comment]
@rpottsoh can I go in and change the version number? Do I need to fork this and do the same commit process again?

**Comment by rpottsoh** [comment]
> can I go in and change the version number? Do I need to fork this and do the same commit process again?

@Selina-Jane nothing this complicated.  It appears as you have modified your forked copy of `canonical-data.json` on the master branch.  Make sure `master` is checked out, `git checkout master`.  Then proceed to modify the file, to update `"version"`, save your changes.  Then you just need to commit your changes and then push to origin/master (or whatever you call your remote copy of this repo).  You will end up with two commits in this PR.  When the PR is finally merged we will squash it (combining your two commits into a single commit).  Essentially the process is the same as you followed when you created the PR except this time you will not be creating a PR, just committing and pushing.

In the future I recommend creating a branch and then committing and pushing your changes with that branch checked out.  

@Insti feel free to expound in more detail on anything I have tried to explain to @Selina-Jane.

**Comment by rpottsoh** [comment]
I should have asked.  @Selina-Jane are you working locally and using git or are you working from the github website?  Either way the process is essentially the same.  Ultimately you want your next round of changes to be committed to your forked copy of the repo (aka origin).  Since your PR is from your master branch anything you commit to that branch will end up being added to this PR, automatically.

If you are working locally and are using `git` to `commit` and to `push` to origin then you can ignore what I have written above in this comment.

**Comment by Selina-Jane** [comment]
I'm really sorry but I accidentally set up a new pull request to change the version number, it is at #923.

**Comment by rpottsoh** [comment]
@Selina-Jane we can get this straightened out.  There are a few ways to go about this.  I am not sure which is the best.

PR #920 was made against master on your fork.  When you modified the file a second time, to update "version", the update should have been committed to master and not to patch-1; this is what lead you down the path of creating a new PR.

@insti and/or anyone else monitoring may want to offer other suggestions than mine to fix this but I am going to go ahead and lay out one way to go about resolving this.....

1.  From the master branch, open the canonical-data.json file.  If you scroll down the file you should find the change you made a few days ago (the basis of this PR).  Assuming you see that change then proceed to increment `"version"` as you did in #923.
1.  Once you have completed your change (I am going to assume you are working from the GitHub site and not locally with git) you need to commit your change.  
    1.  Scroll down to the bottom of the screen and fill in the Description  field (first field) describing the change.
    1.  Add any more information into the box below the field if you want....
1.  "Commit to `master` branch" should be the indicated selection.
1.  Click `Commit changes`.
1.  After completing these steps, revisit this PR.  You should find that it now has two commits instead of  one.
1.  If you were successful then #923 is no longer necessary and you should `close` it and then delete branch `patch-1` from your fork of this repo.


Good luck.

**Comment by rpottsoh** [comment]
Just noticed your second commit.  Nice job!  Thanks taking the time to improve this exercise.

**Comment by rpottsoh** [comment]
This PR will likely be merged shortly.

**Pull request merged**
