### PR TITLE
Move section on updating Test Suite

### PR DESCRIPTION
**Pull request by abdulhannanali**
Moving the section on updating Exercise Test Suite from this repository's `CONTRIBUTING.md` file
to exercism/docs

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
The PR says it moves the section on updating a test suite, but where is it moved to?

**Comment by ErikSchierboom** [comment]
@abdulhannanali Bump. See my question above :)

**Comment by Insti** [comment]
Closing, as this is deleting potentially useful documentation with no and no answers have been provided. about where it has moved to.

There has been a lot of changes in the documentation locations recently, so it is quite likely that this information is also present elsewhere, so please feel free to re-open this if you can direct us to the new location.

**Comment by Stargator** [comment]
from the comment it looks like it will be moved to the exercise/docs repo

**Comment by Insti** [comment]
@Stargator if you'd like to identify the exact document, that would be helpful.

**Pull request closed without merging**
