### PR TITLE
high-scores: Remove report method

### LINKED ISSUE #1456: Simplifying HighScores
In the Ruby track, High Scores works great as an easy exercise for students, but the `report` method makes it a pain to mentor. We want to simplify it such that it doesn't need the giant if/else statement/extracted method/unreadable interpolation anymore. 

Is this interesting for more tracks? In that case, we can change the canonical data.  If it's only an issue in Ruby, we'll change it only there. 

It's in ~@exercism/dart~ , @exercism/csharp @exercism/python @exercism/scala @exercism/delphi @exercism/javascript @exercism/fsharp ?
(cc @pgaspar)

### PR DESCRIPTION
**Pull request by pgaspar**
After the discussion on #1456, @F3PiX and I suggest removing the `report` method entirely. That's the single change in this PR.

closes #1456

### CODE REVIEW

**Comment by F3PiX** [comment]
Do we need to keep this open a bit? 24 hours?

**Comment by rpottsoh** [comment]
I have edited the opening comment so that this PR closes #1456 upon being merged.  It is probably fine to not wait before merging.  #1456 has been open long enough for anyone interested to comment to do so.

**Comment by pgaspar** [comment]
Thanks @rpottsoh. I added the "Closes ..." on the commit itself, which I think has the same effect 🤔

I'm going to merge this shortly. Thanks everyone!

**Comment by rpottsoh** [comment]
You are correct.  I didn't see that.

**Pull request merged**
