### PR TITLE
[armstrong-numbers] Two new test cases

### PR DESCRIPTION
**Pull request by habere-et-dispertire**
Someone look over my shoulder... first use of configlet. :)

Please see: https://github.com/exercism/raku/pull/540#issuecomment-1176314917

### CODE REVIEW

**Review by petertseng — APPROVED** [review]
these values are correct, and the descriptions are factual

please note the number of bits in each input. a 55-bit input was not accepted in https://github.com/exercism/problem-specifications/pull/1487, so reviewers need to evaluate the reasons for not accepting back then and see if they still apply now.

**Comment by habere-et-dispertire** [comment]
What is the interactive prompt or `configlet` way to lint the json file? Oh, and should I also add:

~~~
"scenarios": ["big-integers"],
~~~

The GitHub Action lists three blank fields for the linting error, so I can't see what is wrong via the web.

Thanks! :-)

error-min

**Comment by kytrinyx** [comment]
This is what I'm seeing in the CI failure:

Screen Shot 2022-10-07 at 8 35 58 AM

About the linting, I'm pretty sure configlet is just for track repositories (though there is a `fetch-configlet` script in this repository; I'll ask about that). The README suggests that `yarn` is the way to go here (all the way at the bottom) https://github.com/exercism/problem-specifications#automated-tests

```
yarn run test-one exercises/armstrong-numbers/canonical-data.json
```

**Comment by kytrinyx** [comment]
Oh, also yes, I think adding to the `scenarios` here is a good call!

**Comment by ErikSchierboom** [comment]
@habere-et-dispertire Yes, please add the `big-integer` (singular) scenario.

**Comment by ErikSchierboom** [comment]
> About the linting, I'm pretty sure configlet is just for track repositories

It is. We use prettier to format the JSON, which you can do via:

```shell
yarn install
yarn run format-json
```

**Comment by habere-et-dispertire** [comment]
Thank you all for all the pointers. :-)

I got `yarn` and `ajv` installed. I didn't realize that `yarn` was making the linting changes!

**Review by kytrinyx — APPROVED** [review]
This looks great. Thank you for having the patience to work through all the tweaks and iterations necessary to get this across the finish line.

**Comment by habere-et-dispertire** [comment]
I rather like automation, validation, linting and conformance checking, so it has been a pleasure seeing all the guarding, consistency, and confidence/coherence checking. :-)

**Review by glennj — APPROVED** [review]
LGTM.

**Comment by habere-et-dispertire** [comment]
Thank you one and all: @glennj, @kytrinyx, @petertseng & @ErikSchierboom.
:-)

**Pull request merged**
