### PR TITLE
Rename "Pop Count" to "Eluid's Eggs"

### PR DESCRIPTION
**Pull request by iHiD**
Exercises should be named after their story, not their implementation details.

I'd also like to change the slug, but I'll leave that for another day.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by iHiD** [comment]
@ErikSchierboom Could you get this over the line, and also follow up with a PR to the tracks that have implemented it please (sorry!)

**Comment by ErikSchierboom** [comment]
@exercism/reviewers Could you look at this?

**Review by jiegillet — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
> and also follow up with a PR to the tracks that have implemented it please

Done

**Comment by BNAndras** [comment]
@ErikSchierboom, the exercise title is Eliud's Egg but the blurb in the metadata says Eluid.

**Pull request merged**
