### PR TITLE
forth: added test to check redefining negative numbers

### PR DESCRIPTION
**Pull request by tgujar**
The original version of the test only checks for positive numbers.

```if(/^\d*$/.test(functionName)) throw new Error("Invalid definition");```

An implementation like above will work for positive numbers, but not for negative numbers.

### CODE REVIEW

**Review by wolf99 — COMMENTED** [review]
Should line number 431 also be changed to read "cannot redefine positive numbers", to explicitly describe the difference for that test case?

**Comment by tgujar** [comment]
> Should line number 431 also be changed to read "cannot redefine positive numbers", to explicitly describe the difference for that test case?

Yup I think so, but maybe it should be "cannot redefine non-negative numbers"

**Comment by SleeplessByte** [comment]
cc @exercism/reviewers please review; I have a PR dependent on this waiting to be 💥 merged 🗡️

**Review by SleeplessByte — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]

**Review by ericbalawejder — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks @tgujar!

**Pull request merged**
