### PR TITLE
prime-factors: add further variations

### PR DESCRIPTION
**Pull request by SleeplessByte**
I checked the commit history and conversations on why these exist in JavaScript. They don't really catch edge cases of the _final_ implementation, but they do provide stepping stones when building the implementation.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Can someone sanity check this json? The CI in my opnion is being extremely unhelpful in the error messaging. It's probably a simple issue, but I can't see it because I'm probably looking _over_ it.

**Comment by kotp** [comment]
The title of the PR and the other file doesn't seem to match.  Was that included accidentally?

**Comment by SleeplessByte** [comment]
@kotp the other file is an accident. Will try to remove it!

**Review by kotp — APPROVED** [review]

**Comment by kotp** [comment]
```sh
git rebase -i de4544607a340b625dee5543cde01a42115c9538
```

Delete the unwanted commit and force push should clean it up nicely.  Of course, if rebasing, we could pretend like it was right from the start. ;)

**Review by kotp — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]
This makes the progression a lot nicer. 👍

**Review by valentin-p — APPROVED** [review]

**Pull request merged**
