### PR TITLE
twelve-days: Ensure single line of verse is generated programatically

### PR DESCRIPTION
**Pull request by michaelglass**
I've seen many students solve the problem in this way:

(in elm)
```elm
recite : Int -> Int -> List String
recite start stop =
    List.drop start verses
        |> List.take (stop - start + 1)


verses =
    [ ""
    , "On the first day of Christmas my true love gave to me, a Partridge in a Pear Tree."
    , "On the second day of Christmas my true love gave to me, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the third day of Christmas my true love gave to me, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the fourth day of Christmas my true love gave to me, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the fifth day of Christmas my true love gave to me, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the sixth day of Christmas my true love gave to me, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the seventh day of Christmas my true love gave to me, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the eighth day of Christmas my true love gave to me, eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the ninth day of Christmas my true love gave to me, nine Ladies Dancing, eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the tenth day of Christmas my true love gave to me, ten Lords-a-Leaping, nine Ladies Dancing, eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the eleventh day of Christmas my true love gave to me, eleven Pipers Piping, ten Lords-a-Leaping, nine Ladies Dancing, eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    , "On the twelfth day of Christmas my true love gave to me, twelve Drummers Drumming, eleven Pipers Piping, ten Lords-a-Leaping, nine Ladies Dancing, eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree."
    ]
```

and I think the exercise is more interesting if the student must generate each line.

### CODE REVIEW

**Comment by michaelglass** [comment]
Yah, I don't think this is optimal, but I'm not sure what the best solution is. The problem seems pretty clear.

**Comment by michaelglass** [comment]
Even testing for a gift for a specific day would _hint_ the student away from the example I used in the description.

e.g. `giftFor 5 => "five gold rings"`

**Comment by SleeplessByte** [comment]
You can solve most exercises on exercism using a "shameless green" implementation. I don't think it's always the problem specification / tests that should solve this. 

In this case I'm not sure, but it seems like a change to the description should suffice (wasn't that done recently?)

**Comment by michaelglass** [comment]
e.g. with haskell typeclasses you have the strict definition in code, and the laws that describe the invariants. That being said, I wish we could more easily codify more of the requirements.

**Comment by bitfield** [comment]
As a matter of fact, I think the solution you quoted is optimal! The less code, the less room for bugs.

Sure, generating the text programmatically is more _interesting_, but real software engineering is about solving the problem the best way, not the most interesting for the programmer (or the mentor).

I see solutions all the time which fail to use some simple, obvious, idiomatic language construct or standard library function, because the student assumed that would be _too easy_. Really! Somehow they got the idea that Exercism was about demonstrating your cleverness, or your knowledge of obscure language facilities, rather than doing good engineering. Let's not reinforce that error.

**Comment by michaelglass** [comment]
> As a matter of fact, I think the solution you quoted is optimal! The less code, the less room for bugs.
>
> Sure, generating the text programmatically is more interesting, but real software engineering is about > solving the problem the best way, not the most interesting for the programmer (or the mentor).

I find this argument compelling in the business setting but not in a practice setting. When practicing, I often explicitly want to do something _inefficient_ in the interest of expanding my understanding. E.g. "How would I solve this problem without `if`".

I think the twelve days problem is a much more valuable exercise when students are tasked with doing more, and when students do more, there's more room to spot area for improvement when mentoring.

That being said, I'm not sure how to expand test cases without implying implementation. So be it.

**Comment by bitfield** [comment]
> I find this argument compelling in the business setting but not in a practice setting. When practicing, I often explicitly want to do something inefficient in the interest of expanding my understanding. E.g. "How would I solve this problem without if".

That's one approach to mentoring, for sure, and a valid one, but it's not the one I take. I treat every Exercism solution as a real pull request to a real codebase for a production application, and I apply the same criteria to it as I would any other piece of code: is it correct, readable, idiomatic, simple, and sufficiently performant? Assuming that it is, can it be improved in _any_ way at all? The improvement and refactoring will go on until the code is _perfect_—at least, as far as the student and I can determine. Usually, we both end up learning a lot.

My reasoning is this: what we practice is what we will do for real. Therefore, we should practice doing the right thing, not the wrong thing (every musician knows this, too). This applies even when there are sound _pedagogical_ reasons for doing the 'wrong' thing. The best software engineer is the one who uses the right solution for the problem, not the cleverest or most interesting.

And it's not just a matter of pragmatism: very often, the boring, obvious, straightforward solution is the best _because_ it's obvious. Real programs live a long time (I think I heard Mat Ryer say somewhere that we should write programs as though they were going to be in production for at least ten years. They often are.) Every tiny cognitive obstacle will cost future programmers time and effort to get past it, and endanger the reliability of the code. Small flaws become huge when magnified across large teams and vast codebases, long lapses of time, and many updates and releases.

For it is written in the scriptures, "Clear is better than clever."

**Comment by sshine** [comment]
The solution to this problem that I like the most is one by rbasso [in Haskell](https://exercism.io/tracks/haskell/exercises/twelve-days/solutions/6d40d780e1704972912e7d9efafdafc7).

**Pull request closed without merging**
