### PR TITLE
rna-transcription: Update canonical data

### PR DESCRIPTION
**Pull request by rpottsoh**
I merged #1027 too quickly.  Sorry about that.

I missed a couple of changes to the test data.

First change, bump the version.

### CODE REVIEW

**Comment by rpottsoh** [comment]
removed comment

**Comment by Insti** [comment]
A more descriptive subject than "Update canonical data" would be helpful.

What has been updated?

**Comment by rpottsoh** [comment]
I missed that.  I plan to squash and merge and will note what was changed.

**Comment by Stargator** [comment]
I don't understand, why were the comments removed? I don't see a reasoning or discussion on that.

**Comment by rpottsoh** [comment]
The comment was removed as the three test cases that dealt with invalid input were removed per #902.

**Pull request merged**
