### PR TITLE
clock: add test case for comparing 24:00 and 00:00 clocks

### PR DESCRIPTION
**Pull request by felix91gr**
As explained [here](https://github.com/exercism/rust/pull/635) in the rust branch, this test helped me find a flaw in my solution which otherwise passed all the tests.

Please tell me if I messed up the format! :)

### CODE REVIEW

**Comment by Insti** [comment]
Looks good.
You will need to update the version number at the top of the file.

**Comment by rpottsoh** [comment]
Looks good to me, as @Insti said, just fix the [version](https://github.com/exercism/problem-specifications#test-data-versioning).

**Comment by felix91gr** [comment]
Thank you guys, I've now updated the version from `2.2.1` to `2.3.0` (added a test case)

**Comment by Insti** [comment]
Great! thanks a lot @felix91gr :heart:

**Pull request merged**
