### PR TITLE
Update canonical-data.json

### PR DESCRIPTION
**Pull request by mohamad-shoumar**
Added a check where position of X is not at last position

### CODE REVIEW

**Comment by IsaacG** [comment]
See existing test `28025280-2c39-4092-9719-f3234b89c627`

**Comment by MatthijsBlom** [comment]
Test `28025280-2c39-4092-9719-f3234b89c627` proved insufficient to catch the solution that inspired this test.

**Comment by IsaacG** [comment]
Should we move the discussion to the forum? Changes should be discussed there prior to opening PRs.

**Comment by MatthijsBlom** [comment]
I was not planning on championing this proposal, and will not participate in a forum discussion, sorry.

I'm just dropping by here to clear up a confusion that landed in my GH notifications feed.

The only thing I might otherwise have wanted to add in the future: a better test case would be, I think, a _random_ candidate number ending in `X` that is valid, except that it also contains an `X` in another place (making it invalid). The randomness would be there to signal that nothing special is going on, other than the `X`s.

**Pull request closed without merging**
