### PR TITLE
luhn: Update non-ASCII test case

### PR DESCRIPTION
**Pull request by mienaikage**
Relating to #441

### CODE REVIEW

**Comment by SleeplessByte** [comment]
(@mienaikage we often wait for 3 approvals, but alas)

**Comment by mienaikage** [comment]
Ah, sorry!

**Comment by rpottsoh** [comment]
Another small request.  Please include PR number in commit message, makes it easier to search later.

**Comment by SleeplessByte** [comment]
> Another small request. Please include PR number in commit message, makes it easier to search later.

If you squash merge, this is automatic! (cc @mienaikage)

**Pull request merged**
