### PR TITLE
acronym: Add test case for whitespace prefix + suffix

### PR DESCRIPTION
**Pull request by dolanor**
Follow up from https://github.com/exercism/go/pull/961

### CODE REVIEW

**Comment by rpottsoh** [comment]
problem [description](https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/description.md).

**Comment by dolanor** [comment]
Ok.

**Comment by Insti** [comment]
@dolanor Thanks for the work you put into this, both here and in the Go track. :heart:

The technical aspects of the PR itself were fine, it's just a philosophical difference that means I am not in favor of merging this.

Remember that you are always free to add tests to your local copy of the test suite and suggest additional tests during reviews on the Exercism.io site.

**Comment by dolanor** [comment]
No problem, I wasn't mad. I totally understand your point of view. Too much tedious test is boring and… tedious, so no thanks. And frankly, it took me 10mn max for both PR, so, not a big deal :)

**Pull request closed without merging**
