### PR TITLE
Matrix: Fix input string for test case 'can extract column from non-s…

### PR DESCRIPTION
**Pull request by DagmarTimmreck**
…quare matrix with no corresponding row'

### CODE REVIEW

**Comment by DagmarTimmreck** [comment]
I am really sorry, but in the first PR https://github.com/exercism/problem-specifications/pull/1576 there were extra spaces in the test data.

I hope I didn't break anything and apologize for the extra work.

**Comment by sshine** [comment]
I'm sorry for approving without noticing this. Thank you for putting in the extra work.

Unfortunately, we need to bump the test version once more.

**Comment by sshine** [comment]
@DagmarTimmreck: Could you push another commit that bumps the version to 1.3.0?

I would do this, but since your pull request is made from `master`, I cannot push changes to the pull request. If you make feature branches and create pull requests from them, maintainers of the repo you submit the pull request to can push changes, too. But as a security measure, I suppose, I cannot push to your `master`.

**Comment by yawpitch** [comment]
Got this fixed in #1578 just in case the bad whitespace was triggering an automated test build that might affect students.

**Pull request closed without merging**
