### PR TITLE
[DND-Character] Add raku track as a language supporting dice

### PR DESCRIPTION
**Pull request by habere-et-dispertire**
See: https://docs.raku.org/routine/roll

### CODE REVIEW

**Comment by jiegillet** [comment]
Raku is not "designed to roll dice" [the way Troll is](https://static-curis.ku.dk/portal/files/17117511/Troll-SAC.pdf).
Am I missing something?

**Comment by habere-et-dispertire** [comment]
It does certainly not go as far, but I think it was a design consideration in raku to address a common programming pitfall. Please can you clarify @Util_PM ? I remember some video of yours that expounded on this. Thanks! :-)

**Comment by IsaacG** [comment]
At 22m56s, the presenter is talking about how Perl 6 is written mostly in Perl 6.

Raku has a "roll" function which randomly selects an element from a sequence N times. This is definitely handy when you need to "roll dice" but ... it's just a "select random element" function. I'm not seeing how this is any different from any other language with a "select random element" function.

**Comment by habere-et-dispertire** [comment]
Okay, I don't think I thought this one through enough.
Thank you all for your time and consideration.
:)

**Pull request closed without merging**
