### PR TITLE
Simplify control flow topics

### PR DESCRIPTION
**Pull request by robphoenix**
See https://github.com/exercism/meta/issues/83#issuecomment-324048581

From that conversation...

@robphoenix

> Be good to also consider what to do with topics such as Control-flow (conditionals) - control_flow_(conditionals) or control_flow_conditionals?

@ihiD

> For "control_flow_conditionals" can we just have "conditionals" please?

@kytrinyx

> I think it's worth sorting this out at the TOPICS level. Configlet could do it, but it would seem more like a dark art if it's not listed the way we want it up front.

### CODE REVIEW

**Comment by stkent** [comment]
Anyone in the org AFAIK!

**Comment by Smarticles101** [comment]
Technically, it's possible for someone to not be in the track-maintainers team and thus not have access to push to this repo, but idk of anyone who matches that criteria. Anyone who has read access to a repo can approve changes, but it won't fully count unless they have push access

**Comment by m-a-ge** [comment]
My version is https://github.com/m-a-ge/problem-specifications/blob/issue_887_convert_topics_to_snake_case/TOPICS.txt
What do you think?

**Comment by tleen** [comment]
@m-a-ge should be in a separate PR for discussion?

**Comment by m-a-ge** [comment]
@tleen, I can open one if needed

**Comment by m-a-ge** [comment]
I think it's better to save both topics:
```
control_flow_conditionals
control_flow_loops
```
It will be helpful for some exercises

**Comment by kytrinyx** [comment]
> Can anyone in the org approve changes to this repo or are there official maintainers for it?

I've structured the track maintainers using nested teams so that anyone who gets added as a maintainer to a specific Exercism language track automatically has commit on this repository.

I think eventually we might end up with a dedicated team of people who care a lot about the general curriculum without necessarily caring about any specific language track, at which point we can discuss whether another structure would be better, or whether we should just have a specific `problem-specifications` or `curriculum` team who _also_ has commit.

**Pull request merged**
