### PR TITLE
Fix apophenia error slowing student progress

### PR DESCRIPTION
**Pull request by workingjubilee**
apophenia - noun
"the tendency to perceive a connection or meaningful pattern between unrelated or random things"
compare: pareidolia - noun
"to perceive a specific, often meaningful image in a random or ambiguous visual pattern"
- Merriam Webster's

### CODE REVIEW

**Comment by yawpitch** [comment]
Thanks for the contribution, however can you provide some explanation of how apophenia applies here? As someone who apparently does not have this tendency I see no meaningful value in the change.

Also, your second change appears wrong... on line 27 you perform the doubling on the second digits, when for all other digits that line only acts as a mask to identify which digits to double.

**Comment by yawpitch** [comment]
Note, if this is in reference to one of the most ignorant phrases in human history I'm fine with changing the string, I'd just fix that doubling issue.

**Comment by workingjubilee** [comment]
It is _definitely_ what you are thinking of, yes. I did not wish to give them further resonance by echoing them, as they are well-recorded elsewhere, in appropriate context, and this is not a historical project. Thus the somewhat vague commit remark.

Fixed the issue you noted.

**Comment by rpottsoh** [comment]
@workingjubilee please modify your initial comment to explain what purpose is being served by this pull request.  I am not seeing any logical reason for these changes you have proposed.

**Comment by coriolinus** [comment]
@rpottsoh There exist people who use certain digit strings as a code. Unfortunately, the codes that become well-known are the ones which belong to hate groups, because they tend not to be subtle. 

The removed digit strings include such a code. Nobody is suggesting that its inclusion was anything other than coincidental, but the intent for removing it, in the original commit message, is to keep people--both supporters and victims--from seeing things that aren't really there.

**Comment by sshine** [comment]
I'll spell it out a bit more: 88 means "heil hitler" (8 = h) in some circles.

Having once infiltrated neo-nazi systems, I have an eye for those numbers, too.

I can imagine that someone who was done something similar and whose mental health suffers, it may be somewhat of a fixation. Since we're dealing with minorities, this may be an exaggeration. Then again, I've witnessed three panic attacks in malls over queue distancing in the last month.

I would like to think of this as an act of kindness rather than any attempt at political correctness.

**Comment by rpottsoh** [comment]
Thanks for the explanation.  It is clear to me now.

**Pull request merged**
